name: publish-nuget

on:
  push:
    tags:
    - v*
    branches:
    - master
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/Rdz.cTrader.Library.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install KZRNM Get csproj versions
      id: csproj-version
      uses: kzrnm/get-net-sdk-project-versions-action@v1
      with:
        proj-path: src/Rdz.cTrader.Library/Rdz.cTrader.Library.csproj
    
    - name: Get Project version
      run: |
        $version = "${{steps.csproj-version.outputs.assembly-version}}"
        Write-Host "Detected version: $version"
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: Get .NET info
      run: dotnet --info

    - name: Restore NuGet dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/master')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
